name: precompile

on: [push]

jobs:
  linux:
    name: Test on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: make

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: _build/launcher

  macos:
    name: Test on MacOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: make

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: macos
          path: _build/launcher

  windows:
    name: Test on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile
        run: make
        shell: cmd
        env:
          MAKE: make
          CC: gcc

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: win32
          path: _build/launcher